import "./globals.css";
import type { Metadata } from "next";
import { Saira } from "next/font/google";

import { Header } from "../components/header";
import { DefaultProviders } from "@/components/default-providers";

const saira = Saira({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <DefaultProviders>
          <Header />
          {children}
        </DefaultProviders>
      </body>
    </html>
  );
}
